//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACME.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/myweb/WebService/WebService1.asmx")]
        public string WindowsApplication1_Service_WebService1 {
            get {
                return ((string)(this["WindowsApplication1_Service_WebService1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"pbZX5/8YYrsoAlGPBAD5eZzhAn8+7sOASFZzZ5CF4TZ6HSQuGKRBrD0sT7EXnMsC9pZuX3YC045U1rleuHU6n2y/6PENKYbRbNzP5u+4zfNYz3uEuY839KvXMusplX5blTtPHCznQrI+CFpjV1qfXpLrr3NqT2h+EsLSN41d7ippyaFOn4s6SvUQLC7lFqqAfzXB9msGJuf0e66z96Bx/t7UxspwSgLJUH1kLl8pYYNb59yu9S1ntqedSNNim79TpGxf5U6sIySZ6ZP5f/LIlg==")]
        public string KINGSConnectionString {
            get {
                return ((string)(this["KINGSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=acmesap;Initial Catalog=AcmeSqlSP;Persist Security Info=True;User ID=" +
            "sapdbo;Password=@rmas")]
        public string SPConnectionString1 {
            get {
                return ((string)(this["SPConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=acmesap;Initial Catalog=AcmeSqlSP;Persist Security Info=True;User ID=" +
            "sapdbo;Password=@rmas")]
        public string new01ConnectionString {
            get {
                return ((string)(this["new01ConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"pbZX5/8YYrsoAlGPBAD5eZzhAn8+7sOASFZzZ5CF4Tb3fy+D79ZuyWvaxsd3Z6oPURrVZSOC9YGUCZ4RyJAMYZ/KY4PY14tZ9/YXceodsJEGS8HckWMMhQCRM0Z4PNIehtvBj0s2dXI8UD0Dw/AVAjSc3SaJXa5QjdGeGyetC7meotv06iYp6ymi0+KEvbUF9I1BTSYCm0K9P1cH3fsI60tXR2aRbupo9zFwAve1GKKE4w70f3w9x21dbAthFaFUifna05oOxgqQsM0amg+wRDYaQtoTjwtjTivyeSKe6TQ=")]
        public string lpConnectionString {
            get {
                return ((string)(this["lpConnectionString"]));
            }
            set {
                this["lpConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=acmesap;Initial Catalog=AcmeSql02;Persist Security Info=True;User ID=" +
            "sapdbo;Password=@rmas")]
        public string AcmeSql02ConnectionString {
            get {
                return ((string)(this["AcmeSql02ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=acmesap;Initial Catalog=AcmeSql01;Persist Security Info=True;User ID=" +
            "sapdbo")]
        public string AcmeSql02ConnectionString1 {
            get {
                return ((string)(this["AcmeSql02ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=acmesap;Initial Catalog=AcmeSql98;User ID=sapdbo;Password=@rmas")]
        public string AcmeSql98ConnectionString {
            get {
                return ((string)(this["AcmeSql98ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ACMESRV07;Initial Catalog=EEP;User ID=dbsa;Password=1234")]
        public string EEPConnectionString {
            get {
                return ((string)(this["EEPConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=acmesap;Initial Catalog=AcmeSql02;User ID=sapdbo;Password=@rmas")]
        public string AcmeSql02ConnectionString11 {
            get {
                return ((string)(this["AcmeSql02ConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ACMESRV07;Initial Catalog=acm_ehrdb01;User ID=dbsa;Password=1234")]
        public string acm_ehrdb01ConnectionString {
            get {
                return ((string)(this["acm_ehrdb01ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=acmesap;Initial Catalog=AcmeSqlEEP;User ID=sapdbo;Password=@rmas")]
        public string AcmeSqlEEPConnectionString {
            get {
                return ((string)(this["AcmeSqlEEPConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ACMESRV07;Initial Catalog=EEP;Persist Security Info=True;User ID=sa;P" +
            "assword=1234")]
        public string EEPConnectionString1 {
            get {
                return ((string)(this["EEPConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=acmesap;Initial Catalog=DNN;Integrated Security=True")]
        public string DNNConnectionString {
            get {
                return ((string)(this["DNNConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.40;Initial Catalog=CHIComp16;Persist Security Info=True;User " +
            "ID=webstock;Password=@cmewebstock")]
        public string CHIComp16ConnectionString {
            get {
                return ((string)(this["CHIComp16ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"pbZX5/8YYrsoAlGPBAD5eZzhAn8+7sOASFZzZ5CF4TZPgn+iqqthWqjFKHllorekL+YiPIklvIozfciBlOBKA7RPtMf/m8GeNMbHOy1FhPstcPMXKP5ZPZsnW3A7Ih75omi43XK+qbUp9/wWIqiqaxS6wTsPIjtfjNDtMzMgZaet3Y6ahqtihkPu7F03ZxDFwd3xSl4zkMeE16NBK7fmw5lS/SD8OrsgESwlg+c/YwZIyBvhfJRxPqBPYX1ZbrlmWyhgpbtvc4GizGIuoO/VgQ==")]
        public string SPConnectionString {
            get {
                return ((string)(this["SPConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"pbZX5/8YYrsoAlGPBAD5eZzhAn8+7sOASFZzZ5CF4TZPgn+iqqthWqjFKHllorekL+YiPIklvIozfciBlOBKA7RPtMf/m8GeNMbHOy1FhPsLPumLtfsLEHFxRg2C/cN2osvA8Bc9mZSJ4MfJ7CgtjgsaiXX69LiKK3B/H5QrldYKTzCPRwy3pnZ+7ESInX0zO4k1x0wElK+8vNl8EEjoLNo6Y4MHSYvmSrgzRXuwelrpQWaO6wOqsVB1bKQTwY2ryrTT3D/S1gOCnUqkQwdBrQ==")]
        public string ACMEConnectionString {
            get {
                return ((string)(this["ACMEConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ACMESAP;Initial Catalog=DNN2;Persist Security Info=True;User ID=sapdb" +
            "o;Password=@rmas")]
        public string DNN2ConnectionString {
            get {
                return ((string)(this["DNN2ConnectionString"]));
            }
        }
    }
}
